### ISSUE TITLE
Claim list?

### ISSUE THREAD

**Issue by herohamp** [tarent/loginsrv#128]
What are all the claims that caddy-jwt gets access to? Im trying to allow users based on their gmail domain using caddy-login to login

**Comment by g-w** [comment]
An example for the claims can be found here: 

https://github.com/tarent/loginsrv#the-jwt-token

If you need to add additional information to the claims you can use a [users file](https://github.com/tarent/loginsrv#user-file). For example add a section like this:

```
- origin: Google
  claims:
    role: user
    projects:
      - example
```
