### ISSUE TITLE
Support Arm in docker image

### ISSUE THREAD

**Issue by chedim** [tarent/loginsrv#188]
on Orange Pi 5B using the following compose file: 
```
version: "3"
services:
  loginsrv:
    image: tarent/loginsrv
    ports:
      - 4856:8080
    restart: unless-stopped
```

getting:

`exec /loginsrv: exec format error`
